#!/bin/sh
# Copyright (c) 2005 Silicon Graphics, Inc.
# All rights reserved.
# 
#	Nathan Scott <nathans@sgi.com>
#	14 Sep 2005	Initial version
# 

TRACEOPTS=""
PARSEOPTS=""
SUMMARIZE="-q"	# quiet (no dev/cpu summary by default)
USAGE="Usage: btrace [-s] [-t] [-S] [-a <trace>...] <dev>..."
DIRNAME=`dirname $0`

while getopts "a:stS" c
do
	case $c in
	a)	TRACEOPTS=$TRACEOPTS" -a "$OPTARG" ";;
	s)	PARSEOPTS=$PARSEOPTS" -s";;
	t)	PARSEOPTS=$PARSEOPTS" -t";;
	S)	SUMMARIZE="";;
	\?)	echo $USAGE 1>&2
		exit 2
		;;
	esac
done
PARSEOPTS=${PARSEOPTS}${SUMMARIZE}

shift `expr $OPTIND - 1`
if [ $# -eq 0 ]; then
	echo $USAGE 1>&2
	exit 2
fi

${DIRNAME}/blktrace ${TRACEOPTS} -o- $@ | ${DIRNAME}/blkparse ${PARSEOPTS} -i-
